### PR TITLE
early work for algorithm config support

### PR DESCRIPTION
**Pull request by Opeyem1a**
related to #108 

Adds this structure for the reimplementation of the algorithms
Comments in the code specify, but tldr Configs exist so we can augment how algorithms actually behave and they are not something to be customized by end users, but eventually there will be a simple way to overwrite these configs within a simulation for benchmarking purposes

### CODE REVIEW

**Comment by Opeyem1a** [comment]
Current dependencies on/for this PR:
* main
  * **PR #128** <a href="https://app.graphite.dev/github/pr/Teamable-Analytics/algorithms/128" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Teamable-Analytics/algorithms/128?utm_source=stack-comment).

**Comment by ketphan02** [comment]
As I understand this, we will pass `AlgorithmOption` instead of *args and **kwargs

**Review by justino599 — APPROVED** [review]
As this is "early work", I'll approve it, but I assume all the empty config classes will be filled out with their default configurations?

**Comment by Opeyem1a** [comment]
@justino599 yeah, although some may remain empty/be deleted since not all algorithms currently have/need configs - I hadn't chosen yet and thought it would be nice to keep PRs small and progress moving

**Pull request merged**
